name: Sookyung Park's Blog
url: 'https://sookyungpark.github.io'
description: ''

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'Sookyung Park'
disqus_shortname: sookyungpark
google_analytics: UA-176771371-1

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed
